piro18_Ajax_Pirostagram/post/urls.py
from django.urls import path
from . import views

app_name= 'post'

urlpatterns = [
    path('', views.post_main, name='post_main'),
    path('post_new/', views.post_new, name='post_new'),
    path('like_ajax/', views.like_ajax, name='like_ajax'),
    path('comment_ajax/', views.comment_ajax, name='comment_ajax'),
    path('delete_ajax/', views.delete_ajax, name='delete_ajax'),
    ]
    

piro18_Ajax_Pirostagram/server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls', namespace='post')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

piro18_Ajax_Pirostagram/post/models.py
from django.db.models.deletion import CASCADE
from django.db import models
from django.db.models.fields.related import OneToOneField


class Post (models.Model):
    Image = models.ImageField(upload_to='post_image/%y/%m/%d/')
    title = models.CharField(max_length=300)
    content = models.TextField()
    like= models.BooleanField(default=False) #참거짓 

class Comment (models.Model):
    post = models.ForeignKey(Post, on_delete=CASCADE)
    comment =models.TextField()

piro18_Ajax_Pirostagram/post/forms.py
from .models import Post, Comment
from django import forms


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'Image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

piro18_Ajax_Pirostagram/post/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.csrf import csrf_exempt
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.http.response import JsonResponse
import json
# Create your views here.

def post_main (request):  #메인페이지
    post = Post.objects.all()
    form = CommentForm()
    ctx={
        'post': post,
        'form': form
    }
    return render (request, 'post/post_main.html', ctx)

def post_new(request, post=None):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect( 'post:post_main')
    else:
        form = PostForm(instance=post)
        ctx = {'form': form}
    return render(request, 'post/post_new.html', ctx)


#좋아요 버튼

@ csrf_exempt
def like_ajax (request):
    req = json.loads(request.body) # json.loads를 통해 json을 파이썬 형식으로 바꿔줌 {id:1, type:'like'} 을 아래처럼 바꿔줌
    post_id = req['id']  # id: 1 
    post = Post.objects.get(id=post_id)
    post.like = not(post.like)

    post.save()
    return JsonResponse({'id':post_id})  # #JsonResponse를 통해 형식을 바꿔서 보내줌 {id:1, type:'like'}  """

#댓글 버튼
@csrf_exempt
def comment_ajax(request):
    req = json.loads(request.body)
    post_id = req['id']
    comment_content = req['ct']
    comment = Comment()
    comment.post = get_object_or_404(Post, pk=post_id)
    comment.comment = comment_content
    comment.save()
    return JsonResponse({'id': post_id, 'ct': comment_content, 'comment_id': comment.id})


#삭제 ajax
@csrf_exempt
def delete_ajax(request):
    req = json.loads(request.body)
    comment_id = req['id']
    post_id = req['post_id']
    comment = Comment.objects.get(id=comment_id)
    comment.delete()
    return JsonResponse({'id': comment_id, 'post_id': post_id})

piro18_Ajax_Pirostagram/post/templates/post/post_main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Piro18-instagram</title>
    <script
      src="https://kit.fontawesome.com/6fbcf91afd.js"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <header>
      <div id="top-left">
        <a class="link" href='{% url "post:post_new" %}'
          ><i class="fa-brands fa-instagram"></i
        ></a>
        <strong>|</strong>
        <strong><p>instagram</p></strong>
      </div>
      <input type="search" class="search-box" placeholder="검색" />
      <div class="top-right">
        <i class="fa-solid fa-house"></i>
        <i class="fa-regular fa-paper-plane"></i>
        <i class="fa-regular fa-compass"></i>
        <i class="fa-regular fa-user"></i>
      </div>
    </header>
    <hr />
    <main>
      {% for post in post %}
      <div class="post-id-{{post.id}} container">
        <div>
          <img scr=" {{ post.Image.url}}" />
        </div>
        <div>
          <div>{{post.title}}</div>
          <div class="post-content">{{post.content}}</div>
          <div class="ajax-box">
            <div id="ajax-top-left">
              <button
                class="{{post.like}}"
                id="like-button"
                onclick="onClickLike({{ post.id}})"
              >
                <i class="fa-regular fa-heart"></i>
              </button>
              <i class="fa-regular fa-comment-dots"></i>
              <i class="fa-regular fa-paper-plane"></i>
            </div>
            <div class="comments-{{post.id}}">
              {% for comment in post.comment_set.all %}
              <span class="comment-{{comment.id}} block"
                >{{ comment.comment }}</span
              >
              <button
                class="deletecomment-{{comment.id}}"
                type="submit"
                onclick="onClickDelete({{comment.id}},{{post.id}})"
              >
                삭제
              </button>
              <br />
              {% endfor %}
            </div>
            <div>
              <input
                type="text"
                id="comment-{{post.id}}"
                name="content"
                placeholder="댓글을 입력하세요"
              />
              <button
                class="comment-plus"
                type="submit"
                onclick="onClickComment({{post.id}})"
              >
                댓글
              </button>
            </div>
          </div>
        </div>
      </div>
      <hr />
      {% endfor%}
    </main>

    <script>
      const requestLike = new XMLHttpRequest();

      const onClickLike = (id) => {
        const url = "/like_ajax/";
        requestLike.open("POST", url, true);
        requestLike.setRequestHeader(
          "Content-Type",
          "application/x-www-form-urlencoded"
        );
        requestLike.send(JSON.stringify({ id: id }));
      };

      const likeHandleResponse = () => {
        if (requestLike.status < 400) {
          const { id } = JSON.parse(requestLike.response);
          const buttonclass = document.querySelector(
            `.post-id-${id} #like-button`
          );
          const element = document.querySelector(
            `.post-id-${id} .like_comment`
          );
          if (buttonclass.className === "True") {
            buttonclass.className = "False";
            buttonclass.innerHTML = '<i class="fa-regular fa-heart"></i>';
          } else {
            buttonclass.className = "True";
            buttonclass.innerHTML = '<i class="fas fa-heart"></i>';
          }
        }
      };

      requestLike.onreadystatechange = () => {
        if (requestLike.readyState === XMLHttpRequest.DONE) {
          likeHandleResponse();
        }
      };
    </script>
    <script>
      const requestComment = new XMLHttpRequest();

      const onClickComment = (id) => {
        const ct = document.getElementById(`comment-${id}`).value;
        const url = "/comment_ajax/";
        requestComment.open("POST", url, true);
        requestComment.setRequestHeader(
          "Content-Type",
          "application/x-www-form-urlencoded"
        );
        requestComment.send(JSON.stringify({ id: id, ct: ct }));
      };

      const commentHandleResponse = () => {
        if (requestComment.status < 400) {
          const { id, ct, comment_id } = JSON.parse(requestComment.response);
          const comments = document.querySelector(
            `.post-id-${id} .comments-${id}`
          );
          const makecomment = document.querySelector(
            `.post-id-${id} #comment-${id}`
          );
          const newcomment = ct;
          comments.innerHTML += `<span class = 'comment-${comment_id} block'}>${newcomment}</span>`;
          comments.innerHTML += `<button class = 'deletecomment-${comment_id}' type = 'submit'  onclick='onClickDelete(${comment_id},${id})'>삭제</button>`;
          comments.innerHTML += "<br/>";
          makecomment.value = "";
        }
      };
      requestComment.onreadystatechange = () => {
        if (requestComment.readyState === XMLHttpRequest.DONE) {
          commentHandleResponse();
        }
      };
    </script>
    <script>
      const requestDelete = new XMLHttpRequest();

      const onClickDelete = (id, post_id) => {
        const url = "/delete_ajax/";
        requestDelete.open("POST", url, true);
        requestDelete.setRequestHeader(
          "Content-Type",
          "application/x-www-form-urlencoded"
        );
        requestDelete.send(JSON.stringify({ id: id, post_id: post_id }));
      };

      const deleteHandleResponse = () => {
        if (requestDelete.status < 400) {
          const { id, post_id } = JSON.parse(requestDelete.response);
          const parent = document.querySelector(`.comments-${post_id}`);
          const comment = document.querySelector(`.comment-${id}`);
          const deletebutton = document.querySelector(`.deletecomment-${id}`);
          parent.removeChild(comment);
          parent.removeChild(deletebutton);
        }
      };
      requestDelete.onreadystatechange = () => {
        if (requestDelete.readyState === XMLHttpRequest.DONE) {
          deleteHandleResponse();
        }
      };
    </script>
  </body>
</html>

piro18_Ajax_Pirostagram/post/templates/post/post_new.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Piro18-instagram-create</title>
  </head>
  <body>
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %} {{form.as_p}}
      <button type="submit">저장</button>
    </form>
  </body>
</html>