Week 4/SWIDEA_SITE/posts/urls.py
from django.urls import path
from . import views

app_name ="posts"

urlpatterns= [
    path("", views.posts_list, name="list"),
    path("posts/create/", views.posts_create, name="create"),
    path("posts/<int:pk>/",views. posts_retrieve,  name="retrieve"),
    path("posts/<int:pk>/update/", views.posts_update,  name="update"),
    path("posts/<int:pk>/delete/", views.posts_delete,  name="delete"),

    path("posts/devtool_list", views.devtool_list, name="devtool_list"),
    path("posts/devtool_create", views.devtool_create, name="devtool_create"),
    path("posts/devtool_list/<int:pk>",views. devtool_retrieve,  name="devtool_retrieve"),
    path("posts/devtool_list/<int:pk>/update", views.devtool_update,  name="devtool_update"),
    path("posts/devtool_list/<int:pk>/delete", views.devtool_delete,  name="devtool_delete"),
]

Week 4/SWIDEA_SITE/posts/models.py
from django.db import models
from django.conf import settings


class Tool(models.Model):
    name= models.CharField(max_length=30)
    type= models.CharField(max_length=30)
    tool_content=models.TextField()
    
    def __str__(self):
        return self.name

class Post(models.Model):
    
    title = models.CharField(max_length=64)
    content = models.TextField()
    devtool = models.ForeignKey("Tool", related_name="Tool", on_delete=models.CASCADE, null=True)
    interest = models.IntegerField()
    photo= models.ImageField(blank=True, upload_to='posts/%Y%m%d')
    
    def __str__(self):
        return self.title

Week 4/SWIDEA_SITE/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from posts.models import Post, Tool
from django.http.request import HttpRequest


# post view 설정

def posts_list(request:HttpRequest, *args, **kwargs): #메인페이지 
    posts = Post.objects.all()
    return render(request, "posts/posts_list.html", {"posts":posts})

def posts_retrieve(request:HttpRequest, pk, *args, **kwargs):  #게시글 상세보기
    post = Post.objects.get(id=pk)
    return render(request, "posts/posts_retrieve.html", {'post':post})

def posts_create(request:HttpRequest, *args, **kwargs):
    tools=Tool.objects.all()
    if request.method == "POST":
        tool_pk=request.POST.get('tool', False)
        try:
            toole = Tool.objects.get(pk=tool_pk)
        except Tool.DoesNotExist:
            toole = None
        Post.objects.create(
            title=request.POST["title"],
            interest=request.POST["interest"],
            devtool=toole,
            content=request.POST["content"],
            photo=request.FILES.get("photo",False),
        )
        latest= Post.objects.last()
        return redirect(f"/posts/{latest.pk}/")
    return render(request, "posts/posts_create.html", {'tools':tools})

def posts_delete(request:HttpRequest, pk, *args, **kwargs):
    if request.method == "POST":
        post = Post.objects.get(id=pk)
        post.delete()
    return redirect("/")

def posts_update(request:HttpRequest, pk, *args, **kwargs):
    post = Post.objects.get(id=pk)
    tools=Tool.objects.all()
    context={
        'post':post,
        'tools':tools,
         }
    if request.method == "POST":
        post.title=request.POST["title"]
        post.interest=request.POST["interest"]
        post.devtool=request.POST["devtool"]
        post.content=request.POST["content"]
        post.photo=request.FILES.get("photo",False)
        post.save()
        return redirect(f"/posts/{post.id}")
    return render(request, "posts/posts_update.html", {'context':context})

# devtool view 설정

def devtool_list(request:HttpRequest, *args, **kwargs): #메인페이지 
    tools = Tool.objects.all()
    return render(request, "posts/devtool_list.html", {"tools":tools})

def devtool_retrieve(request:HttpRequest, pk, *args, **kwargs):  #게시글 상세보기
    tool = Tool.objects.get(id=pk)
    return render(request, "posts/devtool_retrieve.html", {'tool':tool})

def devtool_create(request:HttpRequest, *args, **kwargs):
    if request.method == "POST":
        Tool.objects.create(
            name=request.POST["name"],
            type=request.POST["type"],
            tool_content=request.POST["tool_content"],
        )
        return redirect("/posts/devtool_list")
    return render(request, "posts/devtool_create.html")

def devtool_delete(request:HttpRequest, pk, *args, **kwargs):
    if request.method == "POST":
        tool = Tool.objects.get(id=pk)
        try:
            toold = Tool.objects.get(pk=tool)
        except Tool.DoesNotExist:
            toold = None
        tool.delete()
    return redirect("/posts/devtool_list")

def devtool_update(request:HttpRequest, pk, *args, **kwargs):
    tool = Tool.objects.get(id=pk)
    if request.method == "POST":
        tool.name=request.POST["name"]
        tool.type=request.POST["type"]
        tool.tool_content=request.POST["tool_content"]
        tool.save()
        return redirect(f"/posts/devtool_list/{tool.id}")
    return render(request, "posts/devtool_update.html", {"tool":tool})

Week 4/SWIDEA_SITE/posts/templates/posts/devtool_create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>IDEA SITE - MAIN PAGE</title>
  </head>
  <body>
    <header>
      <div><a href="/" class="top_left">My<span>SW Idea</span>Manage</a></strong></div>
      <div class="top_right">
        <a href="{% url 'posts:create' %}" class="idea_register">아이디어 등록</a>
        <a href="/" class="idea_manage">아이디어 관리</a>
        <a href="{% url 'posts:devtool_create'%}" class="devtool_create">개발툴 등록</a> 
        <a href="{% url 'posts:devtool_list'%}" class="devtool_list">개발툴 관리</a> 
      </div>
    </header>
    <div class="tregister_box">
        <b><span>Devtool Register</span></b>
        <p>개발 등록 페이지입니다. 자신이 다룰 수 있는 개발툴을 등록해 보세요!</p>
      <form action="{% url 'posts:devtool_create' %}" method="POST" enctype="multipart/form-data">
        <hr />

        {% csrf_token %}
        <span>이름: <br><input name="name" placeholder="개발툴 이름" value="{{Tool.name}}"/></span>
        <br /> 
        <span>종류: <input name="type" placeholder="종류" /></span>
        <br />
        <span>개발툴 설명: <textarea name="tool_content" placeholder="설명"></textarea></span>
        <br />
          <input type="submit" value="Save" />
      </form>
    </div>  
  </body>
</html>

Week 4/SWIDEA_SITE/posts/templates/posts/devtool_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>IDEA SITE - Devtool_list</title>
  </head>
  <body>
    <header>
      <div><a href="/" class="top_left">My<span>SW Idea</span>Manage</a></strong></div>
      <div class="top_right">
        <a href="{% url 'posts:create' %}" class="idea_register">아이디어 등록</a>
        <a href="/" class="idea_manage">아이디어 관리</a>
        <a href="{% url 'posts:devtool_create'%}" class="devtool_create">개발툴 등록</a> 
        <a href="{% url 'posts:devtool_list'%}" class="devtool_list">개발툴 관리</a> 
      </div>
    </header>
    <div class="tlist_box">
      <b><span>Devtool List🛠️</span></b>
      <p>개발툴 목록 페이지입니다. 자신이 사용가능한 개발들의 목록을 확인해 보세요.</p>
      {%for i in tools %}
        <article>
            <a href="{% url 'posts:devtool_retrieve' i.pk %}"> {{i.name}} </a>
            <span>{{ i.type }}</span>
            <p> {{ i.tool_content }}</p>
            </div>
        </article>
        <hr>
      {% endfor%}
    </div>  
  </body>
</html>

Week 4/SWIDEA_SITE/posts/templates/posts/devtool_retrieve.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>IDEA SITE - Idea retrieve</title>
  </head>
  <body>
    <header>
      <div><a href="/" class="top_left">My<span>SW Idea</span>Manage</a></strong></div>
      <div class="top_right">
        <a href="{% url 'posts:create' %}" class="idea_register">아이디어 등록</a>
        <a href="/" class="idea_manage">아이디어 관리</a>
        <a href="{% url 'posts:devtool_create'%}" class="devtool_create">개발툴 등록</a> 
        <a href="{% url 'posts:devtool_list'%}" class="devtool_list">개발툴 관리</a> 
      </div>
    </header>
    <div class="retrieve_box">
      <b><span>DevTool Detail💡</span></b>
      <p>개발툴 세부내용 페이지입니다. 자신이 다룰 수 있는 개발툴에 대한 상세내용을 확인해보아요.</p>
        <span><br><input name="name" placeholder="개발툴 이름" value="{{tool.name}}"/></span>
        <br /> 
        <span>개발툴 설명: <textarea name="devtool_content" placeholder="설명">{{tool.tool_content}}</textarea></span>
        <br /><hr>
      </form>

      <div>
        <a href="{% url 'posts:devtool_update' tool.pk %}">수정</a>
      </div>
      <div>
        <a href="{% url 'posts:devtool_list'%}">목록</a>
      </div>
      <form action="{% url 'posts:devtool_delete' tool.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" , value="삭제" />
      </form>
    </div>  
  </body>
</html>

Week 4/SWIDEA_SITE/posts/templates/posts/devtool_update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>IDEA SITE - MAIN PAGE</title>
  </head>
  <body>
    <header>
      <div><a href="/" class="top_left">My<span>SW Idea</span>Manage</a></strong></div>
      <div class="top_right">
        <a href="{% url 'posts:create' %}" class="idea_register">아이디어 등록</a>
        <a href="/" class="idea_manage">아이디어 관리</a>
        <a href="{% url 'posts:devtool_create'%}" class="devtool_create">개발툴 등록</a> 
        <a href="{% url 'posts:devtool_list'%}" class="devtool_list">개발툴 관리</a> 
      </div>
    </header>
    <div class="tupdate_box">
        <b><span>Devtool Detail Update</span></b>
        <p>개발툴 세부내용 수정 페이지입니다. 개발툴에 대해 수정사항이 있으면 고쳐보아요!</p>
      <form  method="post" enctype="multipart/form-data">
        <hr />

        {% csrf_token %}
        <span>이름: <br><input name="name" placeholder="개발툴 이름" value="{{tools.name}}"/></span>
        <br /> 
        <span>종류: <input name="type" placeholder="종류" /></span>
        <br />
        <span>개발툴 설명: <textarea name="tool_content" placeholder="설명"></textarea></span>
        <br />
          <input type="submit" value="Save" />
      </form>
    </div>  
  </body>
</html>

Week 4/SWIDEA_SITE/posts/templates/posts/posts_create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>IDEA SITE - MAIN PAGE</title>
  </head>
  <body>
    <header>
      <div><a href="/" class="top_left">My<span>SW Idea</span>Manage</a></strong></div>
      <div class="top_right">
        <a href="{% url 'posts:create' %}" class="idea_register">아이디어 등록</a>
        <a href="/" class="idea_manage">아이디어 관리</a>
        <a href="{% url 'posts:devtool_create'%}" class="devtool_create">개발툴 등록</a> 
        <a href="{% url 'posts:devtool_list'%}" class="devtool_list">개발툴 관리</a> 
      </div>
    </header>
    <div class="iregister_box">
      <b><span>Idea Register💡</span></b>
      <p>아이디어 등록 페이지입니다. 아이디어를 잊지 말고 기록해주세요!</p>
      <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
        <hr />
        {% csrf_token %}
        <span>아이디어명: <br><input name="title" placeholder="아이디어 제목" value="{{Post.title}}"/></span>
        <br />
        <input name="img" placeholder="이미지" type="file" />
        <br />
        <span>아이디어 설명: <textarea name="content" placeholder="설명"></textarea></span>
        <br />
        <span>아이디어 관심도: <input name="interest" placeholder="관심도" /></span>
        <br />
        <select name= "devtool">
          <span> 예상 개발툴: </span>
          {% for i in tools %} 
            <option value="{{i.id}}" name="devtool">{{i.name}}</option>
          {% endfor %}                
        </select>
        <br />
        <div>
          <input type="submit" value="Save" />
        </div>
      </form>
    </div>  
  </body>
</html>

Week 4/SWIDEA_SITE/posts/templates/posts/posts_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>IDEA SITE - MAIN PAGE</title>
  </head>
  <body>
    <header>
      <div><a href="/" class="top_left">My<span>SW Idea</span>Manage</a></strong></div>
      <div class="top_right">
        <a href="{% url 'posts:create' %}" class="idea_register">아이디어 등록</a>
        <a href="/" class="idea_manage">아이디어 관리</a>
        <a href="{% url 'posts:devtool_create'%}" class="devtool_create">개발툴 등록</a> 
        <a href="{% url 'posts:devtool_list'%}" class="devtool_list">개발툴 관리</a>  
      </div>
    </header>
    <div class="mainlist_box">
      <b><span>Idea List💡</span></b>
      <p>나의 아이디어를 잊지 말고 기록해보세요</p>
      {% for i in posts %}
        <article>
            {% if i.photo %}
            <p>
                <img src="{{ i.photo.url }}"/>
            </p><br>
            {% endif %}
            <p><a href="{% url 'posts:retrieve' i.pk %}">{{i.title}}</a></p><br
            <div>
                <p>예상 개발 툴: {{i.title}}</p><br>
                <p>아이디어 관심도: {{ i.interset }}</p>
            </div>
        </article>
        <hr>
      {% endfor%}
    </div>  
  </body>
</html>

Week 4/SWIDEA_SITE/posts/templates/posts/posts_retrieve.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>IDEA SITE - Idea retrieve</title>
  </head>
  <body>
    <header>
      <div><a href="/" class="top_left">My<span>SW Idea</span>Manage</a></strong></div>
      <div class="top_right">
        <a href="{% url 'posts:create' %}" class="idea_register">아이디어 등록</a>
        <a href="/" class="idea_manage">아이디어 관리</a>
        <a href="{% url 'posts:devtool_create'%}" class="devtool_create">개발툴 등록</a> 
        <a href="{% url 'posts:devtool_list'%}" class="devtool_list">개발툴 관리</a> 
      </div>
    </header>
    <div class="retrieve_box">
      <b><span>Idea Detail💡</span></b>
      <p>아이디어 세부내용 페이지입니다. 당신이 구현하려 한 아이디어들을 자세히 살펴보세요.</p>
      <article>
          {% if post.photo %}
          <p>
              <img src="{{ post.photo.url }}"/>
          </p><br>
          {% endif %}
          <h2>{{post.title}}</h2>
          <div>
              <p> 1. 아이디어 관심도 {{ post.interset }}</p>
              <p><a href="{% url 'posts:devtool_retrieve' post.pk%}"> 2. 예상 개발툴 {{ i.devtool }}</a></p>
              <p> 3. 아이디어 설명 {{ post.content }}</p>
          </div>
      </article>
      <div>
        <a href="{% url 'posts:update' post.pk%}">수정</a>
      </div>
      <div>
        <a href="/">목록</a>
      </div>
      <form action="{% url 'posts:delete' post.pk%}" method="post">
        {% csrf_token %}
        <input type="submit" , value="삭제" />
      </form>
    </div>  
  </body>
</html>

Week 4/SWIDEA_SITE/posts/templates/posts/posts_update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>IDEA SITE - MAIN PAGE</title>
  </head>
  <body>
    <header>
      <div><a href="/" class="top_left">My<span>SW Idea</span>Manage</a></strong></div>
      <div class="top_right">
        <a href="{% url 'posts:create' %}" class="idea_register">아이디어 등록</a>
        <a href="/" class="idea_manage">아이디어 관리</a>
        <a href="{% url 'posts:devtool_create'%}" class="devtool_create">개발툴 등록</a> 
        <a href="{% url 'posts:devtool_list'%}" class="devtool_list">개발툴 관리</a> 
      </div>
    </header>
    <div class="iupdate_box">
      <b><span>Idea Detail Update💡</span></b>
      <p>아이디어 세부내용 수정 페이지입니다. 아이디어를 구체화하거나 내용을 변경해 보아요!</p>
      <form method="POST">
        <hr />
        {% csrf_token %}
        <span>아이디어명: <br><input name="title" value="{{Post.title}}"/></span>
        <br />
        <span>Image: <br><input name="img" type="file" /></span>
        <br />
        <span>아이디어 설명: <br><textarea name="content" placeholder="설명">{{Post.content}}</textarea></span>
        <br />
        <span>아이디어 관심도: <input value="{{Post.interest}}" name="interest" placeholder="관심도" /></span>
        <br />
        <select name= "devtool">
          <span> 예상 개발툴: </span>
          {% for i in tools %} 
            <option value="{{i.id}}" name="devtool">{{i.name}}</option>
          {% endfor %}                
          </select>
        <br />
        
        <br />
        <div>
          <input type="submit" value="Save" />
        </div>
      </form>
    </div>  
  </body>
</html>